var translationData = function(cityTitle) {
	return {
		source: {
			title: "Meet and fuck tonight in your area",
			title_replace: "Meet and fuck tonight in " + cityTitle,
			text01: "These women in your neighbourhood",
			text02: "<span class=\"geo-city\">Your Area</span>: 2 SEX REQUESTS!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SEX REQUESTS!",
			text03: "Sign up for free in just",
			timerFinal: "Next",
			text04: "What is your gender?",
			text05: "Woman",
			text06: "Man",
			text07: "When she open<br> the door...",
			text08: "... 30 seconds<br> later!",
			text09: "Have you ever been on a sex date?",
			text10: "No",
			text11: "Yes",
			text12: "She tries to contain<br> yourself...",
			text13: "... but she wants<br> you to fuck her!",
			text14: "Do you use a condom?",
			text15: "No",
			text16: "Yes",
			text17: "How old are you?",
			text18: "Next",
			text19: "When she open<br> the door...",
			text20: "... 30 seconds<br> later!",
			text21: "Choose youre password",
			text22: "Next",
			text23: "She tries to contain<br> yourself...",
			text24: "... but she wants<br> you to fuck her!",
			text25: "What's your email?",
			text26: "Submit",
			text27: "Congratulations!",
			text28: "Please, complete your registration by clicking the confirmation link sent to your email:",
			text29: "Please note! The email may take a few minutes to arrive.",
			text30: "IMPORTANT: If you don't see the confirmation email in your «inbox» folder 5-10 minutes after your registration, please check your «spam/junk» folder.",

			age: "Enter age",
			password: "Enter password",
			email: "Enter email",
			errAge1: "Invalid age. You must be 18+.",
			errPassword1: "Please enter a password.",
			errPassword2: "Password must contain letters and numbers and be 6-16 characters.",
			errEmail1: "Please enter a valid email address.",
			errEmail2: "Email is not valid."
		},
		en: {
			title: "Meet and fuck tonight in your area",
			title_replace: "Meet and fuck tonight in " + cityTitle,
			text01: "These women in your neighbourhood",
			text02: "<span class=\"geo-city\">Your Area</span>: 2 SEX REQUESTS!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SEX REQUESTS!",
			text03: "Sign up for free in just",
			timerFinal: "Next ",
			text04: "What is your gender?",
			text05: "Woman",
			text06: "Man",
			text07: "When she open<br> the door...",
			text08: "... 30 seconds<br> later!",
			text09: "Have you ever been on a sex date?",
			text10: "No",
			text11: "Yes",
			text12: "She tries to contain<br> yourself...",
			text13: "... but she wants<br> you to fuck her!",
			text14: "Do you use a condom?",
			text15: "No",
			text16: "Yes",
			text17: "How old are you?",
			text18: "Next",
			text19: "When she open<br> the door...",
			text20: "... 30 seconds<br> later!",
			text21: "Choose youre password",
			text22: "Next",
			text23: "She tries to contain<br> yourself...",
			text24: "... but she wants<br> you to fuck her!",
			text25: "What's your email?",
			text26: "Submit",
			text27: "Congratulations!",
			text28: "Please, complete your registration by clicking the confirmation link sent to your email:",
			text29: "Please note! The email may take a few minutes to arrive.",
			text30: "IMPORTANT: If you don't see the confirmation email in your «inbox» folder 5-10 minutes after your registration, please check your «spam/junk» folder.",

			age: "Enter age",
			password: "Enter password",
			email: "Enter email",
			errAge1: "Invalid age. You must be 18+.",
			errPassword1: "Please enter a password.",
			errPassword2: "Password must contain letters and numbers and be 6-16 characters.",
			errEmail1: "Please enter a valid email address.",
			errEmail2: "Email is not valid."
		},
		cs: {
			title: "Poznejte dívky ve vašem regionu",
			title_replace: "Poznejte dívky v " + cityTitle,
			text01: "Tyto ženy ve vašem blízkém",
			text02: "<span class=\"geo-city\">Regionu</span>: 2 POŽADAVKY NA SEX!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 POŽADAVKY NA SEX!",
			text03: "Přihlaste se bezplatně již",
			timerFinal: "nyní ",
			text04: "Jaké je vaše pohlaví?",
			text05: "Žena",
			text06: "Muž",
			text07: "Když otevřela<br> dveře...",
			text08: "... o 30 sekund<br> později!",
			text09: "Byli jste někdy na sexuálním rande?",
			text10: "Ne",
			text11: "Ano",
			text12: "Snaží se ovládnout...",
			text13: "...ale chce ji<br> vyšukat!",
			text14: "Používáte kondom?",
			text15: "Ne",
			text16: "Ano",
			text17: "Kolik je vám let?",
			text18: "Dále",
			text19: "Když otevřela<br> dveře...",
			text20: "... o 30 sekund<br> později!",
			text21: "Vyberte si heslo",
			text22: "Dále",
			text23: "Snaží se ovládnout...",
			text24: "...ale chce ji<br> vyšukat!",
			text25: "Jaký je váš e-mail?",
			text26: "Dále",
			text27: "Gratulujeme!",
			text28: "Svou registraci dokončete kliknutím na potvrzovací odkaz, který byl zaslán na váš e-mail, prosím:",
			text29: "Povšimněte si, prosím! Může trvat několik minut, než vám e-mail přijde.",
			text30: "DŮLEŽITÉ: Pokud neuvidíte potvrzovací e-mail ve složce vaší «došlé pošty» do 5-10 minut po vaší registraci, tak prosím, klikněte na složku vaší «nevyžádané/reklamní pošty».",

			age: "Zadejte věk",
			password: "Vyberte si heslo",
			email: "Zadejte e-mail",
			errAge1: "Neplatný věk. Musíte být 18+.",
			errPassword1: "Prosím, vložte heslo.",
			errPassword2: "Heslo musí obsahovat písmena a číslice a musí mít 6-16 znaků.",
			errEmail1: "Prosím zadejte platnou emailovou adresu.",
			errEmail2: "E-mail není platný."
		},
		de: {
			title: "Treffe einheimische Mädchen in Deiner Nähe",
			title_replace: "Treffe einheimische Mädchen in " + cityTitle,
			text01: "Diese Frauen in deiner Nachbarschaft",
			text02: "<span class=\"geo-city\">In Deiner Gegend</span>: 2 SEX-ANFRAGEN!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SEX-ANFRAGEN!",
			text03: "Melden Sie sich kostenlos",
			timerFinal: "jetzt an",
			text04: "Was ist dein Geschlecht?",
			text05: "Frau",
			text06: "Mann",
			text07: "Wenn sie die Tür<br> öffnet ...",
			text08: "... 30 Sekunden<br> später!",
			text09: "Warst du jemals auf einem Sex Date?",
			text10: "Nein",
			text11: "Ja",
			text12: "Sie versucht Dich<br> einzudämmen ...",
			text13: "... aber sie will, <br>dass du sie fickst!",
			text14: "Benutzt du ein Kondom?",
			text15: "Nein",
			text16: "Ja",
			text17: "Wie alt bist Du?",
			text18: "Weiter",
			text19: "Wenn sie die Tür<br> öffnet ...",
			text20: "... 30 Sekunden<br> später!",
			text21: "Wähle dein Passwort",
			text22: "Weiter",
			text23: "Sie versucht Dich<br> einzudämmen ...",
			text24: "... aber sie will, <br>dass du sie fickst!",
			text25: "Wie ist deine E-Mailadresse?",
			text26: "Weiter",
			text27: "Herzlichen Glückwunsch!",
			text28: "Bitte vervollständige deine Registrierung, indem Du auf den Bestätigungslink klickst, der an deine E-Mail gesendet wurde:",
			text29: "Bitte beachte! Es kann einige Minuten dauern, bis die E-Mail eintrifft.",
			text30: "WICHTIG: Wenn Du die Bestätigungs-E-Mail 5-10 Minuten nach Deiner Registrierung nicht in Deinem Ordner \"Posteingang\" siehst, überprüfe bitte Deinen Ordner \"Spam / Junk\".",

			age: "Alter eingeben",
			password: "Passwort eingeben",
			email: "E-Mailadresse eingeben",
			errAge1: "Sie müssen über 18 Jahre alt sein.",
			errPassword1: "Bitte geben Sie ein Passwort ein.",
			errPassword2: "Das Passwort muss alphanumerisch sein und 6-16 Zeichen beinhalten.",
			errEmail1: "Die E-Mail muss echt sein.",
			errEmail2: "Die E-Mail muss echt sein."
		},
		es: {
			title: "Conoce chicas de tu zona",
			title_replace: "Conoce chicas en " + cityTitle,
			text01: "Mujeres en tu vecindario",
			text02: "<span class=\"geo-city\">Tu zona</span>: ¡2 SOLICITUDES DE SEXO!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: ¡2 SOLICITUDES DE SEXO!",
			text03: "Regístrate gratis ahora",
			timerFinal: "mismo ",
			text04: "¿Cuál es tu género?",
			text05: "Mujer",
			text06: "Hombre",
			text07: "Cuando ella abre<br> la puerta...",
			text08: "... ¡30 segundos<br> más tarde!",
			text09: "¿Has tenido una cita sexual antes?",
			text10: "No",
			text11: "Sí",
			text12: "Ella intenta<br> detenerte...",
			text13: "... ¡pero solo quiere <br>tener sexo contigo!",
			text14: "¿Usas condón?",
			text15: "No",
			text16: "Sí",
			text17: "¿Qué edad tienes?",
			text18: "Siguiente",
			text19: "Cuando ella abre<br> la puerta...",
			text20: "... ¡30 segundos<br> más tarde!",
			text21: "Elegir contraseña",
			text22: "Siguiente",
			text23: "Ella intenta<br> detenerte...",
			text24: "... ¡pero solo quiere <br>tener sexo contigo!",
			text25: "¿Cuál es tu correo electrónico?",
			text26: "Siguiente",
			text27: "¡Felicidades!",
			text28: "Por favor, completa tu registro haciendo clic en el enlace de confirmación enviado a tu correo electrónico:",
			text29: "¡Ten en cuenta! El correo electrónico puede tardar unos minutos en llegar.",
			text30: "IMPORTANTE: si no ves el correo electrónico de confirmación en tu carpeta de \"Bandeja de entrada\" entre 5-10 minutos después de tu registro, verifica tu carpeta de \"Spam\".",

			age: "Ingresar edad",
			password: "Ingresar contraseña",
			email: "Ingresar correo electrónico",
			errAge1: "Edad inválida. Debes ser mayor de 18 años.",
			errPassword1: "Porfavor ingresa una contraseña.",
			errPassword2: "La contraseña debe contener letras y números y tener entre 6 y 16 caracteres.",
			errEmail1: "Por favor, introduce una dirección de correo electrónico válida.",
			errEmail2: "El correo electrónico no es válido."
		},
		fr: {
			title: "Rencontrez les filles de votre région",
			title_replace: "Rencontrer des filles locales à " + cityTitle,
			text01: "Ces femmes dans votre quartier",
			text02: "<span class=\"geo-city\">Votre région</span>: 2 DEMANDES DE SEXE !",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 DEMANDES DE SEXE !",
			text03: "Inscrivez-vous gratuitement juste",
			timerFinal: "maintenant ",
			text04: "Quel est votre sexe ?",
			text05: "Femme",
			text06: "Homme",
			text07: "Quand elle ouvre <br>la porte...",
			text08: "... 30 secondes <br>plus tard !",
			text09: "Avez-vous déjà eu un rendez-vous sexuel ?",
			text10: "Non",
			text11: "Oui",
			text12: "Elle essaie de <br>te contenir...",
			text13: "... mais elle veut <br>que tu la baises !",
			text14: "Utilisez-vous un préservatif ?",
			text15: "Non",
			text16: "Oui",
			text17: "Quel âge avez-vous ?",
			text18: "Suivant",
			text19: "Quand elle ouvre <br>la porte...",
			text20: "... 30 secondes <br>plus tard !",
			text21: "Choisissez votre mot de passe",
			text22: "Suivant",
			text23: "Elle essaie de <br>te contenir...",
			text24: "... mais elle veut <br>que tu la baises !",
			text25: "Quel est votre e-mail ?",
			text26: "Suivant",
			text27: "Félicitations!",
			text28: "Veuillez compléter votre inscription en cliquant sur le lien de confirmation envoyé à votre email:",
			text29: "Notez s'il vous plaît que la réception du message peut prendre quelques minutes.",
			text30: "IMPORTANT: Veuillez vérifiez votre dossier «spam / courrier indésirable» si dans 5 ou 10 minutes après votre inscription, vous ne voyez toujours pas de lettre de confirmation dans votre boîte de réception.",

			age: "Entrez l'âge",
			password: "Entrez le mot de passe",
			email: "Entrez l'adresse e-mail",
			errAge1: "Âge invalide Vous devez avoir plus de 18 ans.",
			errPassword1: "S'il vous plaît entrer un mot de passe.",
			errPassword2: "Le mot de passe doit contenir des lettres et des chiffres et comporter entre 6 et 16 caractères.",
			errEmail1: "S'il vous plaît entrer une adresse email valide.",
			errEmail2: "L'email n'est pas valide."
		},
		el: {
			title: "Γνώρισε κορίτσια από την περιοχή σου",
			title_replace: "Γνώρισε κορίτσια από τη " + cityTitle,
			text01: "Αυτές οι γυναίκες είναι στη γειτονιά σου",
			text02: "<span class=\"geo-city\">Η περιοχή σου</span>: 2 ΑΙΤΗΜΑΤΑ ΣΕΞ!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 ΑΙΤΗΜΑΤΑ ΣΕΞ!",
			text03: "Κάνε εγγραφή δωρεάν μόνο σε",
			timerFinal: "τώρα ",
			text04: "Ποιο είναι το φύλο σου;",
			text05: "Γυναίκα",
			text06: "Άνδρας",
			text07: "Όταν ανοίγει <br>την πόρτα…",
			text08: "… 30 δευτερόλεπτα<br> αργότερα!",
			text09: "Έχετε πάει ποτέ σε ραντεβού για σεξ;",
			text10: "Όχι",
			text11: "Ναι",
			text12: "Προσπαθεί να σε<br> συγκρατήσει...",
			text13: "... αλλά θέλει να <br>την γαμήσεις!",
			text14: "Χρησιμοποιείς προφυλακτικό;",
			text15: "Όχι",
			text16: "Ναι",
			text17: "Πόσο χρονών είσαι;",
			text18: "Επόμενο",
			text19: "Όταν ανοίγει <br>την πόρτα…",
			text20: "… 30 δευτερόλεπτα<br> αργότερα!",
			text21: "Επέλεξε τον κωδικό πρόσβασής σου",
			text22: "Επόμενο",
			text23: "Προσπαθεί να σε<br> συγκρατήσει...",
			text24: "... αλλά θέλει να <br>την γαμήσεις!",
			text25: "Ποιο είναι το email σου;",
			text26: "Επόμενο",
			text27: "Συγχαρητήρια!",
			text28: "Παρακαλώ, ολοκλήρωσε την εγγραφή σου κάνοντας κλικ στο σύνδεσμο επιβεβαίωσης που στάλθηκε στο email σου:",
			text29: "Παρακαλώ σημειώστε! Το μήνυμα ηλεκτρονικού ταχυδρομείου μπορεί να διαρκέσει μερικά λεπτά για να φτάσει.",
			text30: "ΣΗΜΑΝΤΙΚΟ: Εάν δεν δεις το μήνυμα επιβεβαίωσης στο φάκελο με τα «εισερχόμενα» σου 5-10 λεπτά μετά την εγγραφή σου, ελέγξε το φάκελο με τα «ανεπιθύμητα» μηνύματα.",

			age: "Βάλε την ηλικία σου",
			password: "Βάλε τον κωδικό πρόσβασης",
			email: "Βάλε το email",
			errAge1: "Μη έγκυρη ηλικία. Πρέπει να είσαι 18+",
			errPassword1: "Παρακαλώ βάλε έναν κωδικό πρόσβασης.",
			errPassword2: "Ο κωδικός πρόσβασης πρέπει να περιέχει γράμματα και αριθμούς και να είναι 6-16 χαρακτήρες.",
			errEmail1: "Παρακαλώ βάλε μια έγκυρη διεύθυνση ηλεκτρονικού ταχυδρομείου.",
			errEmail2: "Το email δεν είναι έγκυρο."
		},
		he: {
			title: "פגוש בנות מקומיות באזורך.",
			title_replace: "פגוש בנות מקומיות ב " + cityTitle,
			text01: "הנשים האלה נמצאות בשכונה שלך",
			text02: "! 2בקשות לסקס: <span class=\"geo-city\">האזור שלך</span>",
			text02_replace: "! 2בקשות לסקס: <span class=\"geo-city\">" + cityTitle + "</span>",
			text03: "הרשם בחינם רק ב",
			timerFinal: "כעת ",
			text04: "מהו המגדר שלך?",
			text05: "אשה",
			text06: "איש",
			text07: "כאשר היא <br>פותחת את הדלת...",
			text08: "!לאחר <br>30 שניות...",
			text09: "האם אי פעם היית בדייט לסקס?",
			text10: "לא",
			text11: "כן",
			text12: "היא מנסה <br>להכיל אותך...",
			text13: "!אבל היא רוצה<br> שתדפוק אותה...",
			text14: "האם אתה משתמש בקונדום?",
			text15: "לא",
			text16: "כן",
			text17: "בן כמה אתה?",
			text18: "הבא",
			text19: "כאשר היא <br>פותחת את הדלת...",
			text20: "!לאחר <br>30 שניות...",
			text21: "בחר סיסמה",
			text22: "הבא",
			text23: "היא מנסה <br>להכיל אותך...",
			text24: "!אבל היא רוצה<br> שתדפוק אותה...",
			text25: "מהי כתובת הדוא\"ל שלך?",
			text26: "הבא",
			text27: "איחולינו!",
			text28: "השלם את הרשמתך על ידי לחיצה על קישור האישור שנשלח לדוא\"ל שלך:",
			text29: "שים לב! יתכן שיהיה עליך להמתין מספר דקות עד להגעת המייל.",
			text30: "חשוב:אם אינך רואה את דוא\"ל האישור ב \"תיבת הדואר הנכנס\" שלך 5-10 דקות לאחר הרישום, בדוק את תיקיית ה- \"דואר זבל / ספאם\" שלך.",

			age: "הזן גיל",
			password: "הזן סיסמה",
			email: "הזן כתובת דוא\"ל",
			errAge1: "גיל לא חוקי. עליך להיות מעל גיל 18",
			errPassword1: "הזן סיסמה",
			errPassword2: "הסיסמה חייבת להכיל אותיות ומספרים ולהיות בת 6-16 תווים",
			errEmail1: "הזן כתובת דוא\"ל חוקית",
			errEmail2: "כתובת דוא\"ל שהוזנה אינה חוקית"
		},
		hr: {
			title: "Upoznajte lokalne djevojke u vašoj oblasti",
			title_replace: "Upoznajte lokalne djevojke u " + cityTitle,
			text01: "Ove žene u vašem susjedstvu",
			text02: "<span class=\"geo-city\">Vaša oblast</span>: 2 ZAHTJEVA ZA SEKS!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 ZAHTJEVA ZA SEKS!",
			text03: "Pristupite besplatno za",
			timerFinal: "sada ",
			text04: "Koji je vaš spol?",
			text05: "Žena",
			text06: "Muškarac",
			text07: "Kada ona otvori <br>vrata...",
			text08: "... 30 sekundi<br> kasnije!",
			text09: "Da li ste ikad bili na seks sastanku?",
			text10: "Ne",
			text11: "Da",
			text12: "Pokušava se<br> suzdržati...",
			text13: "... ali želi <br>da je tucaš!",
			text14: "Da li koristite kondom?",
			text15: "Ne",
			text16: "Da",
			text17: "Koliko godina imate?",
			text18: "Dalje",
			text19: "Kada ona otvori <br>vrata...",
			text20: "... 30 sekundi<br> kasnije!",
			text21: "Izaberite svoju lozinku",
			text22: "Dalje",
			text23: "Pokušava se<br> suzdržati...",
			text24: "... ali želi <br>da je tucaš!",
			text25: "Koji je vaš e-mail?",
			text26: "Dalje",
			text27: "Čestitamo!",
			text28: "Molimo, dovršite registriranje klikom na poveznicu potvrde poslatu na e-poštu:",
			text29: "Molimo zapamtite! Može potrajati nekoliko minuta da stigne e-pošta.",
			text30: "VAŽNO: ako ne vidite potvrdu e-poštu u vašem spremniku, 5-10 minuta nakon registriranja, molimo provjerite mapu  neželjene pošte.",

			age: "Upišite godine",
			password: "Upišite lozinku",
			email: "Upišite e-mail",
			errAge1: "Nevažeća dob. Morate imati 18+.",
			errPassword1: "Molimo unesite zaporku.",
			errPassword2: "Zaporka mora sadržavati brojeve i slova te imati 6-16 karaktera.",
			errEmail1: "Molimo unesite važeću adresu e-pošte.",
			errEmail2: "E-pošta nije važeća."
		},
		hu: {
			title: "Találkozz helyi csajokkal a környékeden",
			title_replace: "Találkozz helyi csajokkal " + cityTitle,
			text01: "Ezek a nők a szomszédságodban",
			text02: "<span class=\"geo-city\">A környékeden</span>: 2 SZEX KÉRÉS!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SZEX KÉRÉS!",
			text03: "Regisztrálj ingyen",
			timerFinal: "most ",
			text04: "Mi a nemed?",
			text05: "Nő",
			text06: "Férfi",
			text07: "Amikor kinyitja<br> az ajtót...",
			text08: "... 30 másodperccel<br> később!",
			text09: "Voltál már szexrandin?",
			text10: "Nem",
			text11: "Igen",
			text12: "Megpróbál visszafogott<br> lenni...",
			text13: "... de azt szeretné,<br> ha megdugnád őt!",
			text14: "Használsz óvszert?",
			text15: "Nem",
			text16: "Igen",
			text17: "Milyen idős vagy?",
			text18: "Következő",
			text19: "Amikor kinyitja<br> az ajtót...",
			text20: "... 30 másodperccel<br> később!",
			text21: "Válassz egy jelszót",
			text22: "Következő",
			text23: "Megpróbál visszafogott<br> lenni...",
			text24: "... de azt szeretné,<br> ha megdugnád őt!",
			text25: "Mi az email címed?",
			text26: "Következő",
			text27: "Gratulálunk!",
			text28: "Kérjük véglegesítsd a regisztrációd a linkre kattintva az emailben amit következő email címre küldtünk:",
			text29: "Megjegyzés! Az email megérkezése igénybe vehet néhány percet.",
			text30: "FONTOS: Ha 5-10 perc múlva nem látod a visszaigazoló emailt a postafiókodban, kérlek nézd meg a «spam/junk» mappádat is.",

			age: "Életkor megadása",
			password: "Jelszó megadása",
			email: "Email megadása",
			errAge1: "Érvénytelen évszám. Kizárólag 18+.",
			errPassword1: "Adj meg egy jelszót.",
			errPassword2: "A jelszó tartalmazzon betűket és számokat is, minimum 6, maximum 16 karakter.",
			errEmail1: "Kérjük adj meg egy valós email címet.",
			errEmail2: "Az email cím nem valós."
		},
		it: {
			title: "Incontra ragazze che vivono nella tua zona",
			title_replace: "Incontra ragazze a " + cityTitle,
			text01: "Queste donne si trovano nella tua zona",
			text02: "<span class=\"geo-city\">La tua zona</span>: 2 RICHIESTE DI SESSO!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 RICHIESTE DI SESSO!",
			text03: "Iscriviti gratuitamente in soli",
			timerFinal: "ora ",
			text04: "Qual è il tuo sesso?",
			text05: "Donna",
			text06: "Uomo",
			text07: "Quando lei apre<br> la porta...",
			text08: "... 30 secondi<br> dopo!",
			text09: "Sei mai andato a un incontro di sesso?",
			text10: "No",
			text11: "Sì",
			text12: "Lei prova a <br>farti controllare...",
			text13: "... ma in realtà vuole<br> che la scopi!",
			text14: "Usi il preservativo?",
			text15: "No",
			text16: "Sì",
			text17: "Quanti anni hai?",
			text18: "Successivo",
			text19: "Quando lei apre<br> la porta...",
			text20: "... 30 secondi<br> dopo!",
			text21: "Scegli la tua password",
			text22: "Successivo",
			text23: "Lei prova a <br>farti controllare...",
			text24: "... ma in realtà vuole<br> che la scopi!",
			text25: "Qual è il tuo indirizzo email?",
			text26: "Successivo",
			text27: "Complimenti!",
			text28: "Completare la registrazione facendo clic sul collegamento di conferma inviato alla propria email:",
			text29: "Tieni presente! L'email potrebbe richiedere alcuni minuti per arrivare.",
			text30: "IMPORTANTE: se non vedi il messaggio di conferma nella tua \"Posta in arrivo\" tra 5-10 minuti dopo la registrazione, controlla la cartella \"Spam\".",

			age: "Inserisci l'età",
			password: "Inserisci la password",
			email: "Inserisci l'email",
			errAge1: "Età sbagliata. Devi avere più di 18 anni.",
			errPassword1: "Si prega, di inserire una password.",
			errPassword2: "La password deve contenere lettere e numeri e avere tra 6 e 16 caratteri.",
			errEmail1: "Si prega di inserire un indirizzo email valido.",
			errEmail2: "L'email non è valida."
		},
		nl: {
			title: "Ontmoet lokale meisjes in je buurt",
			title_replace: "Ontmoet lokale meisjes in " + cityTitle,
			text01: "Deze vrouwen in je buurt",
			text02: "<span class=\"geo-city\">Jouw buurt</span>: 2 SEKS VERZOEKEN!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SEKS VERZOEKEN!",
			text03: "Meld je gewoon gratis aan",
			timerFinal: "nu ",
			text04: "Wat is je geslacht?",
			text05: "Vrouw",
			text06: "Man",
			text07: "Als ze de <br>deur opent...",
			text08: "... 30 seconden<br> later!",
			text09: "Ben je ooit op eens seks date geweest?",
			text10: "Nee",
			text11: "Ja",
			text12: "Ze probeert zichzelf<br> te beheersen...",
			text13: "... maar ze wil dat<br> je haar neukt!",
			text14: "Gebruikt je een condoom?",
			text15: "Nee",
			text16: "Ja",
			text17: "Hoe oud ben je?",
			text18: "Volgende",
			text19: "Als ze de <br>deur opent...",
			text20: "... 30 seconden<br> later!",
			text21: "Kies je wachtwoord",
			text22: "Volgende",
			text23: "Ze probeert zichzelf<br> te beheersen...",
			text24: "... maar ze wil dat<br> je haar neukt!",
			text25: "Wat is je e-mail?",
			text26: "Volgende",
			text27: "Gefeliciteerd!",
			text28: "Om uw registratie te voltooien, klikt u op uw e-mail:",
			text29: "Het bericht naar uw e-amil kan enkele minuten duren om aan te komen.",
			text30: "BELANGRIJK: als je geen berichten hebt ontvangen in je inbox, controleer dan de spam tussen 5 en 10  minuten na de registratie.",

			age: "Vul leeftijd in",
			password: "Vul wachtwoord in",
			email: "Vul e-mailadres in",
			errAge1: "Ongeldige leeftijd Je moet ouder zijn dan 18 jaar.",
			errPassword1: "Voer een wachtwoord in.",
			errPassword2: "Het wachtwoord moet letters en cijfers bevatten en tussen 6 en 16 tekens bevatten.",
			errEmail1: "Voer alstublieft een geldig e-mailadres in.",
			errEmail2: "De e-mail is niet geldig."
		},
		fi: {
			title: "Tapaa paikallisia tyttöjä alueellasi",
			title_replace: "Tapaa paikallisia tyttöjä " + cityTitle + "issa",
			text01: "Nämä naiset naapurustossasi",
			text02: "<span class=\"geo-city\">Alueesi</span>: 2 sukupuolipyyntöä!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 sukupuolipyyntöä!",
			text03: "Rekisteröidy ilmaiseksi vain",
			timerFinal: "nyt ",
			text04: "Mikä on sukupuolesi?",
			text05: "Nainen",
			text06: "Mies",
			text07: "Kun hän <br>avaa oven ...",
			text08: "... 30 sekuntia<br> myöhemmin!",
			text09: "Oletko koskaan ollut seksipäivänä?",
			text10: "Ei",
			text11: "Joo",
			text12: "Hän yrittää hillitä<br> itseään ...",
			text13: "... mutta hän haluaa<br> sinun vittu!",
			text14: "Käytätkö kondomia?",
			text15: "Ei",
			text16: "Joo",
			text17: "Kuinka vanha olet?",
			text18: "Seuraava",
			text19: "Kun hän <br>avaa oven ...",
			text20: "... 30 sekuntia<br> myöhemmin!",
			text21: "Valitse salasanasi",
			text22: "Seuraava",
			text23: "Hän yrittää hillitä<br> itseään ...",
			text24: "... mutta hän haluaa<br> sinun vittu!",
			text25: "Mikä on sähköpostisi?",
			text26: "Seuraava",
			text27: "Onneksi olkoon!",
			text28: "Ole hyvä ja täytä ilmoituksesi klikkaamalla sähköpostiviestiin lähetettyä vahvistuslinkkiä:",
			text29: "Varoitus! Vahvistusviesti voi kestää muutaman minuutin.",
			text30: "TÄRKEÄÄ: Jos et näe vahvistusviestiä kansiossa \"Saapuneet\" 5-10 minuuttia rekisteröinnin jälkeen, tarkista roskapostikansiosi.",

			age: "Anna ikä",
			password: "Kirjoita salasana",
			email: "Syötä sähköposti",
			errAge1: "Väärä ikä. Sinun on oltava vähintään 18-vuotias.",
			errPassword1: "Anna salasana.",
			errPassword2: "Salasanan tulee sisältää kirjaimia ja numeroita, ja siinä on oltava 6 - 16 merkkiä.",
			errEmail1: "Anna kelvollinen sähköpostiosoite.",
			errEmail2: "Sähköposti on virheellinen."
		},
		no: {
			title: "Møt lokale jenter i ditt område",
			title_replace: "Møt lokale jenter i " + cityTitle,
			text01: "Disse kvinnene i nabolaget ditt",
			text02: "<span class=\"geo-city\">Ditt område</span>: 2 SEX FORESPØRSELER!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SEX FORESPØRSELER!",
			text03: "Registrer deg gratis på bare",
			timerFinal: "nå ",
			text04: "Hva er ditt kjønn?",
			text05: "Kvinne",
			text06: "Mann",
			text07: "Når hun åpner<br> døren ...",
			text08: "... 30 sekunder<br> senere!",
			text09: "Har du noen gang vært på sexdate?",
			text10: "Nei",
			text11: "Ja",
			text12: "Hun prøver å <br>beholde seg ...",
			text13: "... men hun vil at du<br> skal knulle henne!",
			text14: "Bruker du kondom?",
			text15: "Nei",
			text16: "Ja",
			text17: "Hvor gammel er du?",
			text18: "Neste",
			text19: "Når hun åpner<br> døren ...",
			text20: "... 30 sekunder<br> senere!",
			text21: "Velg ditt passord",
			text22: "Neste",
			text23: "Hun prøver å <br>beholde seg ...",
			text24: "... men hun vil at du<br> skal knulle henne!",
			text25: "Hva er epost adressen din?",
			text26: "Neste",
			text27: "Gratulerer!",
			text28: "Vennligst fullfør registreringen din ved å klikke på din epost:",
			text29: "Det er mulig epost meldingen tar noen minutter å bli levert.",
			text30: "VIKTIG: Hvis du ikke har sett noen beskjed i din «Innboks», vennligst sjekk «Søppelpost/Spam» mappen mellom 5 og 10 minutter etter registreringen.",

			age: "Angi alder",
			password: "Oppgi passord",
			email: "Skriv inn e-post",
			errAge1: "Feil alder Du må være over 18 år gammel.",
			errPassword1: "Vennligst skriv inn et passord.",
			errPassword2: "Passordet må inneholde bokstaver og tall og har mellom 6 og 16 tegn.",
			errEmail1: "Vennligst skriv inn en gyldig e-postadresse.",
			errEmail2: "E-postadressen er ikke gyldig."
		},
		da: {
			title: "Mød lokale piger i dit område",
			title_replace: "Mød lokale piger i " + cityTitle,
			text01: "Disse kvinder i dit kvarter",
			text02: "<span class=\"geo-city\">Dit område</span>: 2 SEX-ANMODNINGER!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SEX-ANMODNINGER!",
			text03: "Tilmeld dig gratis bare",
			timerFinal: "nu ",
			text04: "Hvad er dit køn?",
			text05: "Kvinde",
			text06: "Mand",
			text07: "Når hun åbner<br> døren ...",
			text08: "... 30 sekunder<br> senere!",
			text09: "Har du nogensinde været på en sex-date?",
			text10: "Ingen",
			text11: "Ja",
			text12: "Hun prøver<br> at holde sig<br> inde ...",
			text13: "... men hun vil have <br>dig til at kneppe hende!",
			text14: "Bruger du kondom?",
			text15: "Ingen",
			text16: "Ja",
			text17: "Hvor gammel er du?",
			text18: "Næste",
			text19: "Når hun åbner<br> døren ...",
			text20: "... 30 sekunder<br> senere!",
			text21: "Vælg din adgangskode",
			text22: "Næste",
			text23: "Hun prøver<br> at holde sig<br> inde ...",
			text24: "... men hun vil have <br>dig til at kneppe hende!",
			text25: "Hvad er din email?",
			text26: "Næste",
			text27: "Tillykke!",
			text28: "Udfyld venligst din registrering ved at klikke på bekræftelseslinket sendt til din e-mail:",
			text29: "Advarsel! Bekræftelsesmeddelelsen kan tage et par minutter at ankomme.",
			text30: "VIGTIGT: Hvis du ikke ser bekræftelsesmeddelelsen i din \"Indbakke\" mappe mellem 5-10 minutter efter din registrering, skal du tjekke din \"Spam\" mappe.",

			age: "Indtast alder",
			password: "Indtast adgangskode",
			email: "Indtast e-mail",
			errAge1: "Forkert alder. Du skal være mindst 18 år gammel.",
			errPassword1: "Indtast venligst et kodeord.",
			errPassword2: "Adgangskoden skal indeholde bogstaver og tal og have mellem 6 og 16 tegn.",
			errEmail1: "Indtast venligst en gyldig email-adresse.",
			errEmail2: "E-mail er forkert."
		},
		pl: {
			title: "Poznawaj miejscowe dziewczyny w Twojej okolicy",
			title_replace: "Poznawaj miejscowe dziewczyny w " + cityTitle,
			text01: "To kobiety z Twojej okolicy",
			text02: "<span class=\"geo-city\">Twoja okolica</span>: 2 ZAPROSZENIA NA SEKS!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 ZAPROSZENIA NA SEKS!",
			text03: "Zarejestruj się za darmo już",
			timerFinal: "teraz ",
			text04: "Podaj swoją płeć.",
			text05: "Kobieta",
			text06: "Mężczyzna",
			text07: "Gdy otwiera<br> drzwi...",
			text08: "... 30 sekund<br> później!",
			text09: "Czy kiedykolwiek byłeś na seks-randce?",
			text10: "Nie",
			text11: "Tak",
			text12: "Stara się<br> opanować...",
			text13: "... ale chce, żebyś<br> ją przerżnął!",
			text14: "Czy używasz prezerwatyw?",
			text15: "Nie",
			text16: "Tak",
			text17: "Ile masz lat?",
			text18: "Dalej",
			text19: "Gdy otwiera<br> drzwi...",
			text20: "... 30 sekund<br> później!",
			text21: "Wybierz hasło",
			text22: "Dalej",
			text23: "Stara się<br> opanować...",
			text24: "... ale chce, żebyś<br> ją przerżnął!",
			text25: "Podaj Twój adres e-mail",
			text26: "Dalej",
			text27: "Gratulacje!",
			text28: "Prosimy o zgłoszenie swojej rejestracji klikając adres email:",
			text29: "Wysłanie wiadomości email może potrwać kilka minut.",
			text30: "WAŻNE: Jeśli w folderze  «skrzynka odbiorcza» nie ma wiadomości potwierdzającej, 5-10 minut po rejestracji, sprwadź w folderze «kosz/spam»",

			age: "Wpisz wiek",
			password: "Wpisz hasło",
			email: "Wpisz adres e-mail",
			errAge1: "Nieprawidłowy wiek. Musisz mieć ukończone 18 lat.",
			errPassword1: "Wpisz hasło.",
			errPassword2: "Hasło musi zawierać litery i cyfry i posiadać od 6 do 16 znaków.",
			errEmail1: "Wpisz adres email.",
			errEmail2: "Nieprawidłowy email."
		},
		pt: {
			title: "Conheça raparigas locais na sua área",
			title_replace: "Conheça raparigas locais em " + cityTitle,
			text01: "Estas mulheres na sua vizinhança",
			text02: "<span class=\"geo-city\">A Sua Área</span>: 2 PEDIDOS DE SEXO!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 PEDIDOS DE SEXO!",
			text03: "Registe-se de graça",
			timerFinal: "agora ",
			text04: "Qual é o seu sexo?",
			text05: "Mulher",
			text06: "Homem",
			text07: "Quando ela abrir<br> a porta...",
			text08: "... 30 segundos<br> depois!",
			text09: "Alguma vez teve um encontro sexual?",
			text10: "Não",
			text11: "Sim",
			text12: "Ela tenta<br> conter-se...",
			text13: "... mas ela quer<br> que a fodas!",
			text14: "Utiliza preservativo?",
			text15: "Não",
			text16: "Sim",
			text17: "Qual a sua idade?",
			text18: "Seguinte",
			text19: "Quando ela abrir<br> a porta...",
			text20: "... 30 segundos<br> depois!",
			text21: "Escolha a sua senha",
			text22: "Seguinte",
			text23: "Ela tenta<br> conter-se...",
			text24: "... mas ela quer<br> que a fodas!",
			text25: "Qual é o seu e-mail?",
			text26: "Seguinte",
			text27: "Parabéns!",
			text28: "Por favor, preencha o seu cadastro clicando no seu email:",
			text29: "Por favor, tenha em mente! A mensagem pode demorar alguns minutos para chegar.",
			text30: "IMPORTANTE: Se não viu nenhuma mensagem na sua \"Caixa de entrada\", verifique a sua pasta \"Spam / Spam\" entre 5 e 10 minutos após o seu registo.",

			age: "Introduza a idade",
			password: "Introduza a senha",
			email: "Introduza o e-mail",
			errAge1: "Idade não válida Deve ter 18 anos ou mais",
			errPassword1: "Digite a sua senha",
			errPassword2: "A senha deve ser alfanumérica e entre 6 e 16 caracteres.",
			errEmail1: "Digite o seu endereço de email",
			errEmail2: "O email não é válido."
		},
		ro: {
			title: "Întâlnește fete din zona ta",
			title_replace: "Întâlnește fete care locuiesc în " + cityTitle,
			text01: "Ceste femei sunt din cartierul tău",
			text02: "<span class=\"geo-city\">Zona ta</span>: 2 CERERI DE SEX!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 CERERI DE SEX!",
			text03: "Înscrie-te gratuit în doar",
			timerFinal: "acum ",
			text04: "Care este sexul tău?",
			text05: "Femeie",
			text06: "Bărbat",
			text07: "Când ea deschide<br> ușa...",
			text08: "... 30 de secunde<br> mai târziu!",
			text09: "Ai fost vreodată la o întâlnire sexuală?",
			text10: "Nu",
			text11: "Da",
			text12: "Ea încearcă să <br>te stăpânească...",
			text13: "... dar vrea să<br> i-o tragi!",
			text14: "Folosești prezervativ?",
			text15: "Nu",
			text16: "Da",
			text17: "Ce vârstă ai?",
			text18: "Următoare",
			text19: "Când ea deschide<br> ușa...",
			text20: "... 30 de secunde<br> mai târziu!",
			text21: "Alege-ți parola",
			text22: "Următoare",
			text23: "Ea încearcă să <br>te stăpânească...",
			text24: "... dar vrea să<br> i-o tragi!",
			text25: "Care este adresa ta de email?",
			text26: "Următoare",
			text27: "Felicitări!",
			text28: "Te rugăm să finalizezi înregistrarea făcând clic pe link-ul de confirmare trimis la adresa ta de email:",
			text29: "Te rugăm să reții! Poate dura câteva minute până ajunge emailul.",
			text30: "IMPORTANT: Dacă nu vezi emailul de confirmare în folderul «Inbox» la 5-10 minute de la înregistrare, verifică folderul «spam/junk».",

			age: "Introdu vârsta",
			password: "Introdu parola",
			email: "Introdu adresa de email",
			errAge1: "Vârsta nevalidă. Trebuie să ai peste 18 ani.",
			errPassword1: "Te rog alege o parolă.",
			errPassword2: "Parola trebuie să conțină litere și numere și să aibă 6-16 caractere.",
			errEmail1: "Indrodu o adresă de email.",
			errEmail2: "Te rugăm să folosești o adresă de e-mail validă."
		},
		ru: {
			title: "Встретьтесь с местными девушками в вашем районе",
			title_replace: "Встретьтесь с местными девушками в г. " + cityTitle,
			text01: "Эти женщины живут рядом с вами",
			text02: "<span class=\"geo-city\">В вашем районе</span>: 2 ЗАПРОСА НА СЕКС!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 ЗАПРОСА НА СЕКС!",
			text03: "Бесплатная регистрация",
			timerFinal: "сейчас ",
			text04: "Укажите ваш пол",
			text05: "Женщина",
			text06: "Мужчина",
			text07: "Когда она <br>открывает дверь...",
			text08: "... через 30<br> секунд!",
			text09: "Вы когда-нибудь ходили на секс-свидание?",
			text10: "Нет",
			text11: "Да",
			text12: "Она пытается <br>сдерживать<br> себя...",
			text13: "... но она хочет,<br> чтобы вы ее<br> трахнули!",
			text14: "Вы используете презерватив?",
			text15: "Нет",
			text16: "Да",
			text17: "Сколько вам лет?",
			text18: "Далее",
			text19: "Когда она <br>открывает дверь...",
			text20: "... через 30<br> секунд!",
			text21: "Выберите ваш пароль",
			text22: "Далее",
			text23: "Она пытается <br>сдерживать<br> себя...",
			text24: "... но она хочет,<br> чтобы вы ее<br> трахнули!",
			text25: "Укажите вашу электронную почту",
			text26: "Далее",
			text27: "Поздравляем!",
			text28: "Для подтверждения регистрации пройдите по ссылке, отправленной на ваш электронный адрес:",
			text29: "Отправка электронного письма может занять несколько минут.",
			text30: "ВАЖНО: Если вы не видите электронного письма подтверждения в папке «Входящие» через 5-10 минут после регистрации, проверьте папку «Спам / нежелательная почта».",

			age: "Введите ваш возраст",
			password: "Введите пароль",
			email: "Введите электронную почту",
			errAge1: "Вам должно быть 18+.",
			errPassword1: "Пожалуйста, введите пароль.",
			errPassword2: "Пароль должен содержать как минимум одну цифру и состоять из 6-16 символов.",
			errEmail1: "Пожалуйста, введите ваш Email.",
			errEmail2: "Email неверный."
		},
		sk: {
			title: "Stretnite miestne dievčatá vo vašom okolí",
			title_replace: "Stretnite miestne dievčatá v " + cityTitle,
			text01: "Tieto ženy sú vo vašom okolí",
			text02: "<span class=\"geo-city\">Vaše okolie</span>: 2 SEXUÁLNE PONUKY!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SEXUÁLNE PONUKY!",
			text03: "Prihláste sa zdarma",
			timerFinal: "teraz ",
			text04: "Aké je vaše pohlavie?",
			text05: "Žena",
			text06: "Muž",
			text07: "Keď otvorí<br> dvere...",
			text08: "... o 30 sekúnd<br> neskôr!",
			text09: "Boli ste niekedy na sexuálnom rande?",
			text10: "Nie",
			text11: "Áno",
			text12: "Snaží sa byť<br> pokojná...",
			text13: "... ale chce, aby<br> ste mali sex!",
			text14: "Používate kondóm?",
			text15: "Nie",
			text16: "Áno",
			text17: "Koľko máte rokov?",
			text18: "Ďalej",
			text19: "Keď otvorí<br> dvere...",
			text20: "... o 30 sekúnd<br> neskôr!",
			text21: "Vyberte si heslo",
			text22: "Ďalej",
			text23: "Snaží sa byť<br> pokojná...",
			text24: "... ale chce, aby<br> ste mali sex!",
			text25: "Aký je váš email?",
			text26: "Ďalej",
			text27: "Blahoželáme!",
			text28: "Prosím, dokonči svoju registráciu tým, že klikneš na potvrdzovací link, ktorý ti bol zaslaný na email:",
			text29: "Prosím ber na vedomie, že doručenie e-mailu môže trvať niekoľko minút.",
			text30: "DÔLEŽITÉ: Pokiaľ potvrdzovací email neuvidíte vo vašom priečinku «Doručené» do 5-10 minút od vašej registrácie, skontrolujte priečinok «Spam».",

			age: "Vložte vek",
			password: "Vložte heslo",
			email: "Vložte email",
			errAge1: "Nesprávny vek. Musíš mať aspoň 18 rokov.",
			errPassword1: "Prosím zadajte heslo.",
			errPassword2: "Heslo musí obsahovať písmená a čísla a mať 6-16 znakov.",
			errEmail1: "Prosím zadajte platnú emailovú adresu.",
			errEmail2: "Emailová adresa je neplatná."
		},
		sl: {
			title: "Spoznajte lokalna dekleta v svojem kraju",
			title_replace: "Spoznajte lokalna dekleta v " + cityTitle,
			text01: "Te ženske v vaši soseski",
			text02: "<span class=\"geo-city\">Vaš kraj</span>: 2 ZAHTEVI ZA SEKS!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 ZAHTEVI ZA SEKS!",
			text03: "Registrirajte se brezplačno",
			timerFinal: "zdaj ",
			text04: "Kakšen je vaš spol?",
			text05: "Ženski",
			text06: "Moški",
			text07: "Ko bo odprla<br> vrata...",
			text08: "... 30 sekund<br> kasneje!",
			text09: "Ste že kdaj bili na seks zmenku?",
			text10: "Ne",
			text11: "Da",
			text12: "Poskuša se<br> zadržati...",
			text13: "... ampak želi si,<br> da jo pofukaš!",
			text14: "Uporabljate kondom?",
			text15: "Ne",
			text16: "Da",
			text17: "Koliko let imate?",
			text18: "Naprej",
			text19: "Ko bo odprla<br> vrata...",
			text20: "... 30 sekund<br> kasneje!",
			text21: "Izberite svoje geslo",
			text22: "Naprej",
			text23: "Poskuša se<br> zadržati...",
			text24: "... ampak želi si,<br> da jo pofukaš!",
			text25: "Kakšen je vaš e-poštni naslov?",
			text26: "Naprej",
			text27: "Čestitamo!",
			text28: "Dokončajte svojo registracijo s klikom na potrditveno povezavo, poslano na vaš e-poštni naslov:",
			text29: "Upoštevajte! Pošiljanje e-poštnega sporočila lahko traja nekaj minut.",
			text30: "POMEMBNO: Če potrditvenega e-poštnega sporočila v mapo «prejeto» ne prejmete 5–10 minut po registraciji, preverite mapo «neželeno/vsiljena pošta».",

			age: "Vnesite starost",
			password: "Vnesite geslo",
			email: "Vnesite e-poštni naslov",
			errAge1: "Neveljavna starost. Morate imeti 18+ let.",
			errPassword1: "Vnesite geslo.",
			errPassword2: "Geslo mora vsebovati črke in številke, od 6 do 16 znakov.",
			errEmail1: "Vnesite veljaven e-poštni naslov.",
			errEmail2: "E-poštni naslov ni veljaven."
		},
		sv: {
			title: "Möt lokala tjejer i ditt område",
			title_replace: "Träffa lokala tjejer i " + cityTitle,
			text01: "Dessa kvinnor finns i ditt grannskap",
			text02: "<span class=\"geo-city\">Ditt område</span>: 2 SEXFÖRFRÅGNINGAR!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 SEXFÖRFRÅGNINGAR!",
			text03: "Registrera dig gratis på bara",
			timerFinal: "nu ",
			text04: "Vad är ditt kön?",
			text05: "Kvinna",
			text06: "Man",
			text07: "När hon öppnar<br> dörren ...",
			text08: "... 30 sekunder<br> senare!",
			text09: "Har du någonsin varit på en sexdejt?",
			text10: "Nej",
			text11: "Ja",
			text12: "Hon försöker<br> hålla dig<br> lugn ...",
			text13: "... men hon vill<br> att du ska knulla<br> henne!",
			text14: "Använder du kondom?",
			text15: "Nej",
			text16: "Ja",
			text17: "Hur gammal är du?",
			text18: "Nästa",
			text19: "När hon öppnar<br> dörren ...",
			text20: "... 30 sekunder<br> senare!",
			text21: "Välj ditt lösenord",
			text22: "Nästa",
			text23: "Hon försöker<br> hålla dig<br> lugn ...",
			text24: "... men hon vill<br> att du ska knulla<br> henne!",
			text25: "Vad är din email-adress?",
			text26: "Nästa",
			text27: "Grattis!",
			text28: "Vänligen fyll i din registrering genom att klicka på länken för bekräftelse som skickas till din e-postadress:",
			text29: "Varning! Bekräftelsemeddelandet kan ta några minuter att komma fram.",
			text30: "VIKTIGT: Om du inte ser bekräftelsemeddelandet i mappen \"Inkorg\" mellan 5-10 minuter efter registreringen, kolla din \"Spam\" mapp.",

			age: "Ange ålder",
			password: "Skriv in lösenord",
			email: "Skriv in e-mail",
			errAge1: "Fel ålder. Du måste vara minst 18 år gammal.",
			errPassword1: "Vänligen ange ett lösenord.",
			errPassword2: "Lösenordet måste innehålla bokstäver och siffror och ha mellan 6 och 16 tecken.",
			errEmail1: "Ange en giltig e-postadress.",
			errEmail2: "E-postmeddelandet är felaktigt."
		},
		tr: {
			title: "Bölgenizdeki yerel kızlarla tanışın",
			title_replace: cityTitle + "'taki yerel kızlarla tanışın",
			text01: "Bu kadınlar mahallenizde",
			text02: "<span class=\"geo-city\">Bölgeniz</span>: 2 CİNSEL İLİŞKİ TALEBİ!",
			text02_replace: "<span class=\"geo-city\">" + cityTitle + "</span>: 2 CİNSEL İLİŞKİ TALEBİ!",
			text03: "Hemen ücretsiz olarak kaydolun",
			timerFinal: "şimdi ",
			text04: "Cinsiyetiniz nedir?",
			text05: "Kadın",
			text06: "Erkek",
			text07: "Kapıyı açtığı<br> zaman...",
			text08: "... 30 saniye<br> sonra!",
			text09: "Hiç seks randevusunda bulundun mu?",
			text10: "Hayır",
			text11: "Evet",
			text12: "Kendini tutmaya<br> çalışıyor...",
			text13: "... ama senin onu <br>becermeni istiyor!",
			text14: "Prezervatif kullanıyor musun?",
			text15: "Hayır",
			text16: "Evet",
			text17: "Kaç yaşındasın?",
			text18: "Sonraki",
			text19: "Kapıyı açtığı<br> zaman...",
			text20: "... 30 saniye<br> sonra!",
			text21: "Parolanızı seçin",
			text22: "Sonraki",
			text23: "Kendini tutmaya<br> çalışıyor...",
			text24: "... ama senin onu <br>becermeni istiyor!",
			text25: "E-postanız nedir?",
			text26: "Sonraki",
			text27: "Tebrikler!",
			text28: "Lütfen e-postanıza gönderilen onay linkini tıklayarak kayıt işleminizi tamamlayın:",
			text29: "Uyarı! Onay mesajının gelmesi birkaç dakika sürebilir.",
			text30: "ÖNEMLİ: Kaydolduktan sonraki 5-10 dakika arasında \"Gelen Kutusu\" klasörünüzde onay mesajını bulamazsanız, \"Spam\" klasörünüzü kontrol edin.",

			age: "Yaş girin",
			password: "Parolanı gir",
			email: "E-posta girin",
			errAge1: "Yanlış yaş. En az 18 yaşında olmalısınız.",
			errPassword1: "Lütfen bir şifre girin.",
			errPassword2: "Şifre, harf ve rakam içermeli ve 6 ile 16 karakter arasında olmalıdır.",
			errEmail1: "Lütfen geçerli bir e-posta adresi girin.",
			errEmail2: "E-posta yanlış."
		},
	}
};

var optPushTrls = {
	source: {
		confirmBtnClose: "Later",
		confirmBtnAllow: "Chat Now"
	},
	en: {
		confirmBtnClose: "Later",
		confirmBtnAllow: "Chat Now"
	},
	da: {
		confirmBtnClose: "Senere",
		confirmBtnAllow: "Chat nu"
	},
	de: {
		confirmBtnClose: "Später",
		confirmBtnAllow: "JETZT CHATTEN"
	},
	es: {
		confirmBtnClose: "Despues",
		confirmBtnAllow: "Chatear ahora"
	},
	pt: {
		confirmBtnClose: "Depois",
		confirmBtnAllow: "Bate-papo agora"
	},
	it: {
		confirmBtnClose: "Poi",
		confirmBtnAllow: "Chatta ora"
	},
	fr: {
		confirmBtnClose: "Plus tard",
		confirmBtnAllow: "Discuter maintenant"
	},
	pl: {
		confirmBtnClose: "Później",
		confirmBtnAllow: "Czatuj teraz"
	},
	tr: {
		confirmBtnClose: "Sonra",
		confirmBtnAllow: "Şimdi sohbet et"
	},
	no: {
		confirmBtnClose: "Etterpå",
		confirmBtnAllow: "Nettprat nå"
	},
	nl: {
		confirmBtnClose: "Dan",
		confirmBtnAllow: "Chat nu"
	},
	fi: {
		confirmBtnClose: "Myöhemmin",
		confirmBtnAllow: "Chat nyt"
	},
	sv: {
		confirmBtnClose: "Senare",
		confirmBtnAllow: "Chatta nu"
	},
	ro: {
		confirmBtnClose: "Mai târziu",
		confirmBtnAllow: "VORBEȘTE ACUM"
	},
	ru: {
		confirmBtnClose: "Не сейчас",
		confirmBtnAllow: "Включить чат"
	},
	cs: {
		confirmBtnClose: "Později",
		confirmBtnAllow: "CHATOVAT HNED"
	},
	hu: {
		confirmBtnClose: "Később",
		confirmBtnAllow: "CSET MOST"
	},
	el: {
		confirmBtnClose: "Αργότερα",
		confirmBtnAllow: "ΣΥΝΟΜΙΛΗΣΕ ΤΩΡΑ"
	},
	sl: {
		confirmBtnClose: "Kasneje",
		confirmBtnAllow: "KLEPETAJTE ZDAJ"
	},
	sk: {
		confirmBtnClose: "Neskôr",
		confirmBtnAllow: "ODPÍŠ TERAZ"
	},
	hr: {
		confirmBtnClose: "Kasnije",
		confirmBtnAllow: "ČAVRLJATI SADA"
	},
	he: {
		extNameAge: "אשלי, 26",
		confirmBtnClose: "יותר מאוחר",
		confirmBtnAllow: "נדבר עכשיו"
	},
	bg: {
		extNameAge: "Ашли, на 26 г.",
		confirmBtnClose: "По-късно",
		confirmBtnAllow: "ЧАТ СЕГА"
	}
};

function initTranslations(cityTitle, isCityTranslation) {
	var translation = translationData(cityTitle);

	var availableLang = translation_available(translation);

	if(!isCityTranslation) {
		for (var x in translation["source"]) {
			replace_text(availableLang, x, translation, isCityTranslation);
		}
	} else {
		var cityArr = ['title_replace', 'text02_replace'];

		for (var x in cityArr) {
			replace_text(availableLang, cityArr[x], translation, isCityTranslation);
		}
	}
}

function replace_text(lang, text, translation, isCityTranslation) {
	if (isCityTranslation && text.indexOf('_replace') !== -1) {
		var x = document.getElementById(text.replace('_replace', ''));
	} else {
		var x = document.getElementById(text);
	}

	if (x && translation[lang][text] != undefined) {
		if(x.placeholder != undefined) {
			x.placeholder = translation[lang][text];
		} else if(x.tagName === 'IFRAME') {
			x.src = translation[lang][text];
		} else {
			x.innerHTML = translation[lang][text];
		}
	} else {
		//console.log("element not Found: " + text);
	}
}

function translation_available(objTrls) {
	if (objTrls[browserLang]) {	
			language = browserLang; // for errors in main.js
		return browserLang;
	} else {
		console.log("translation not Found: " + browserLang);
			language = "source"; // for errors in main.js
		return "source";
	}
}

function getParameterByName(name) {
	name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
	var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
		results = regex.exec(location.search);
	return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
}

function detect_language() {
	var forceLang = getParameterByName("lang");

	if (forceLang) {
		return forceLang;
	} else {
		var userLang = navigator.languages && navigator.languages[0] || navigator.language || navigator.userLanguage;
		if (userLang == "zh-CN" || userLang == "zh-SG" || userLang == "zh-MY" || userLang == "zh-CHS") {
			userLang = "zh-Hans";
		} else if (userLang == "zh-HK" || userLang == "zh-MO" || userLang == "zh-TW" || userLang == "zh-CHT") {
			userLang = "zh-Hant";
		} else if (userLang == "no" || userLang == "nb" || userLang == "nb-NO" || userLang == "nn-NO") {
			userLang = "no";
		} else if (userLang.length > 2) {
			userLang = userLang[0] + userLang[1];
		}
		return userLang;
	}
}
var cityTitle = '';
var browserLang = detect_language();
document.body.classList.add("lang-" + browserLang);
var zip = 0;

// Call translation function
initTranslations(cityTitle, false);

function changeCity(data) {
	data.city["pt"] = data.city["pt-BR"];
	data.cnames["pt"] = data.cnames["pt-BR"];

	if (data.pc) {
		zip = data.pc;
	}
	if (data.city[browserLang] && data.city[browserLang].length) {
		cityTitle = data.city[browserLang];
		initTranslations(cityTitle, true);
	}
}

setTimeout(function() {
	if (geoRefData) {
		changeCity(geoRefData);
	} else {
		var request = new XMLHttpRequest();
		request.open('GET', 'https://fdatajsext.com/ExtService.svc/getextparams', true);

		request.onload = function() {
			if (request.status >= 200 && request.status < 400) {
				var data = JSON.parse(request.responseText);
				changeCity(data);
			} else {
				console.log('Server returned an error');
			}
		};

		request.onerror = function() {
			console.log('Error: ' + request.status);
		};

		request.send();
	}
}, 700);